[book]
authors = ["Avery"]
language = "en"
multilingual = false
src = "lit"
title = "Yaifl Docs"

[build]
create-missing = true
[output.html]
mathjax-support = true
additional-css = ["assets/mdbook-admonish.css"]

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
