module Yaifl.Test.Common where

import Yaifl.Prelude

import Breadcrumbs
import Data.Char (isSpace)
import Language.Haskell.TH
import Language.Haskell.TH.Quote hiding (quoteExp)
import Yaifl

import qualified Data.Text as T

import Yaifl.Effects.Print
import Yaifl.Text.Verb
import Yaifl.Parser (printPrompt)
import Yaifl.Effects.Input (waitForInput)

import Yaifl.ObjectSpecifics
import Yaifl.Effects.ObjectQuery
import Yaifl.Rulebooks.ActionProcessing
import Yaifl.Effects.Interpreters
import Yaifl.ActionCollection
import Yaifl.Rulebooks.Run
import Yaifl.Run
import Yaifl.Effects.RuleEffects
import Yaifl.Actions.GoesWith (ActionParameter(NoParameter))
import Yaifl.Actions.Args (ActionOptions(ActionOptions))

expQQ :: (String -> Q Exp) -> QuasiQuoter
expQQ quoteExp = QuasiQuoter quoteExp notSupported notSupported notSupported where
  notSupported _ = fail "Quotation in this context is not supported"

wrappedText :: QuasiQuoter
wrappedText = expQQ
  (return . LitE . StringL . toString . T.strip . newlinesToWrap . unindent . tabsToSpaces . toText)

lineIndent :: Text -> Int
lineIndent = T.length . T.takeWhile (== ' ')

minimumIndent :: Text -> Maybe Int
minimumIndent =
  listToMaybe . sort . map lineIndent
    . filter (\t -> T.empty /= T.dropWhile isSpace t) . lines

unindent :: Text -> Text
unindent s =
  case lines s of
    h : t ->
      let
        unindentedHead = T.dropWhile (== ' ') h
        minimumTailIndent = minimumIndent . unlines $ t
        unindentedTail = case minimumTailIndent of
          Just indent -> map (T.drop indent) t
          Nothing -> t
      in unlines $ unindentedHead : unindentedTail
    [] -> ""

tabsToSpaces :: Text -> Text
tabsToSpaces = T.replace "\t" " "

newlinesToWrap :: Text -> Text
newlinesToWrap = foldl' (\acc -> \case
  "" -> acc <> "\n" <> (if fmap snd (unsnoc acc) == Just '\n' then "" else "\n")
  x -> if T.empty == acc || T.last acc == '\n' then acc <> x else acc <> " " <> x) "" . lines

testHarness ::
  forall wm a.
  HasStandardProperties wm
  => WMHasObjSpecifics wm
  => HasCallStack
  => Bool
  -> Text
  -> [Text]
  -> ConstructionOptions wm
  -> WorldConstruction wm a
  -> IO Text
testHarness allTenses fullTitle actionsToDo conOptions initWorld = do
  fst <<$>> runGame (runPrintPure @(World wm)) runInputAsBuffer (blankWorld (conValues conOptions) (activityCollectionBuilder conOptions) (responseCollectionBuilder conOptions)) blankActionCollection $ do
      output <- withSpan' "test run" fullTitle $ do
        withSpan' "worldbuilding" fullTitle $ do
          newWorld
          evalStateLocal (ActionCollector $ initialExtraActions conOptions) initWorld
          -- this just moves the actions from the indexed, static, standard library collection
          -- into the dynamic collection
          -- we do it here because we need to copy over changes to actions and we can't modify WrappedActions directly
          addStandardActions
        --withSpan "world verification" fullTitle $ do
        let runWorld suffix = do
              withSpan' ("run " <> suffix) fullTitle $ do
                wa <- get @(WorldActions wm)
                unless (suffix == "") $ printLn suffix
                --when I write a proper game loop, this is where it needs to go
                failHorriblyIfMissing (runRulebook Nothing False (wa ^. #whenPlayBeginsRulebook) ())
                setInputBuffer actionsToDo
                runTurnsFromBuffer
                (w2 :: World wm) <- get
                let (x, _) = runPureEff $ runStateShared w2 $ do
                      -- take it down and flip it around
                      msgList <- gets (view $ #messageBuffer % #buffer % reversed)
                      return $ (mconcat . map show) msgList
                pure $ case w2 ^. #metadata % #errorLog of
                  [] -> x <> "\n"
                  _ -> x <> "\n"
                  -- xs -> x <> "\nEncountered the following errors:  \n" <> unlines (reverse xs)
        w <- get
        if allTenses
          then do
            mconcat <$> sequence [ (do
              put (updateNarrative x y w)
              runWorld ("Tense: " <> show y <> " | Viewpoint: " <> show x)) | x <- universe, y <- universe ]
          else runWorld ""
      flush
      pure output

updateNarrative ::
  VerbPersonage
  -> Tense
  -> World wm
  -> World wm
updateNarrative p t w = w & #adaptiveNarrative % #narrativeViewpoint .~ p & #adaptiveNarrative % #tense .~ t

readTraceId :: IO TraceID
readTraceId = TraceID <$> readFileBS "traceid.temp"

fromI7TestMe :: Text -> [Text]
fromI7TestMe = map T.strip . T.splitOn "/"

-- | Run all turns from buffer and return per-action (command, output) pairs.
-- Each pair represents one command and the output generated by that command.
-- The first pair has an empty command and contains the initial world state output.
testHarnessPerAction ::
  forall wm a.
  HasStandardProperties wm
  => WMHasObjSpecifics wm
  => HasCallStack
  => Bool
  -> Text
  -> [Text]
  -> ConstructionOptions wm
  -> WorldConstruction wm a
  -> IO [(Text, Text)]
testHarnessPerAction _allTenses fullTitle actionsToDo conOptions initWorld = do
  fst <<$>> runGame (runPrintPure @(World wm)) runInputAsBuffer (blankWorld (conValues conOptions) (activityCollectionBuilder conOptions) (responseCollectionBuilder conOptions)) blankActionCollection $ do
      output <- withSpan' "test run" fullTitle $ do
        withSpan' "worldbuilding" fullTitle $ do
          newWorld
          evalStateLocal (ActionCollector $ initialExtraActions conOptions) initWorld
          addStandardActions
        wa <- get @(WorldActions wm)
        failHorriblyIfMissing (runRulebook Nothing False (wa ^. #whenPlayBeginsRulebook) ())

        -- Capture initial state (before any commands)
        (wInitial :: World wm) <- get
        let (initialOutput, _) = runPureEff $ runStateShared wInitial $ do
              msgList <- gets (view $ #messageBuffer % #buffer % reversed)
              modify (#messageBuffer % #buffer .~ [])
              return $ T.strip $ mconcat $ map show msgList

        setInputBuffer actionsToDo

        -- Run turns, capturing output after each
        results <- runTurnsFromBufferCapturing wa []

        -- Prepend initial state
        pure $ ("", initialOutput) : results

      flush
      pure output

    where
      runTurnsFromBufferCapturing wa acc = do
        b <- use @(Metadata wm) #bufferedInput
        case b of
          [] -> pure acc
          _ -> do
            modify @(World wm) (#messageBuffer % #buffer .~ [])
            cmd <- waitForInput
            let actionOpts = ActionOptions False False
            printPrompt actionOpts
            case cmd of
              Nothing -> runTurnsFromBufferCapturing wa acc
              Just actualInput -> do
                withStyle (Just bold) $ printText actualInput
                void $ parseAction actionOpts [NoParameter] actualInput
                void $ runRulebook Nothing False (wa ^. #turnSequence) ()
                (w2 :: World wm) <- get
                let (turnOutput, _) = runPureEff $ runStateShared w2 $ do
                      msgList <- gets (view $ #messageBuffer % #buffer % reversed)
                      modify @(World wm) (#messageBuffer % #buffer .~ [])
                      return $ T.strip $ mconcat $ map show msgList

                runTurnsFromBufferCapturing wa (acc ++ [(actualInput, turnOutput)])